language: java

jdk:
- oraclejdk8

before_install:
  - wget http://services.gradle.org/distributions/gradle-3.0-bin.zip
  - unzip gradle-3.0-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.0
  - export PATH=$GRADLE_HOME/bin:$PATH

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
- gradle check 
- gradle assemble 
- gradle build 
- gradle test 