language: java

jdk:
- oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
- gradle check --debug
- gradle assemble --debug
- gradle build --debug
- gradle test --debug