language: java

jdk:
- oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
- gradle check --debug
- gradle assemble --debug
- gradle build --debug
- gradle test --debug